name: Terraform Preprod Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  terraform-cd:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/preprod

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:

      # --------------------------------
      # 1. Checkout
      # --------------------------------

      - name: Checkout Repository
        uses: actions/checkout@v4


      # --------------------------------
      # 2. Setup Terraform
      # --------------------------------

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      # --------------------------------
      # 3. Azure Login
      # --------------------------------

      - name: Azure Login
        shell: bash
        run: |
          az login \
            --service-principal \
            --username "$ARM_CLIENT_ID" \
            --password "$ARM_CLIENT_SECRET" \
            --tenant "$ARM_TENANT_ID"

          az account set \
            --subscription "$ARM_SUBSCRIPTION_ID"


      # --------------------------------
      # 4. Verify Azure Login
      # --------------------------------

      - name: Verify Azure Login
        shell: bash
        run: |
          az account show --output table


      # --------------------------------
      # 5. Terraform Init
      # --------------------------------

      - name: Terraform Init
        run: terraform init


      # --------------------------------
      # 6. Terraform Format
      # --------------------------------

      - name: Terraform Format
        run: terraform fmt -check -recursive


      # --------------------------------
      # 7. Terraform Validate
      # --------------------------------

      - name: Terraform Validate
        run: terraform validate


      # --------------------------------
      # 8. Terraform Plan
      # --------------------------------

      - name: Terraform Plan
        run: terraform plan -out=tfplan


      # --------------------------------
      # 9. Terraform Apply
      # --------------------------------

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan